creation_rules:
  - path_regex: ^talos/talsecret\.sops\.ya?ml$
    age: age1da2cywfkg9hp6v39jvj9qcmqz4n8w3gm6nqj5vygu7e0zzgnp5psne9wlx
    encrypted_regex: '^(.*)$'
  - path_regex: ^kubernetes/.*\.sops\.ya?ml$
    age: age1da2cywfkg9hp6v39jvj9qcmqz4n8w3gm6nqj5vygu7e0zzgnp5psne9wlx
    encrypted_regex: '^(data|stringData)$'
