apiVersion: v1
kind: Secret
metadata:
    name: nas-credentials
    namespace: longhorn-system
type: Opaque
stringData:
    CIFS_USERNAME: ENC[AES256_GCM,data:Vw+3ehJkg6E=,iv:b/NTJ+bvifFKQRrrXpZO8IUzdh/W/xwe9zkDPniLV1Y=,tag:NX5j8w44vYWkrehZQHxqFQ==,type:str]
    CIFS_PASSWORD: ENC[AES256_GCM,data:BY6rQmipGSnd6JoIAADQ6jdPRCg=,iv:Y79C8hS9XZCFfmHMcFF2Co0z3YBMIttXADIyRmt4Dq4=,tag:aRbPpgrN35uRdc8+eecaWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSkJhSUgvWWpud0RDZFJF
            T0R6Tk5lbjFpbUY4T3dwNk92cHNaVFkvZm1zCmNYc3RrTnJqdlJUUjIrb2MwT0NV
            K2ZhVC9yeG5tVW4vWTJTcmYyK040ckUKLS0tIFExSkVTbGRyZFMrRWtsVlBvL3d5
            NnpOS00rQmV2Tm9QK0tROFQvYUIyRTAKIHQDTHP3JExVqwKGNCiUDdMU9j5edNqx
            1EHfUQQuir/mf1sYA9u9BSN5wLtFQzTYjCMdOhLLttU5UmYhMM763Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1da2cywfkg9hp6v39jvj9qcmqz4n8w3gm6nqj5vygu7e0zzgnp5psne9wlx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T17:06:49Z"
    mac: ENC[AES256_GCM,data:47e5ANYvVKBdU+u1MXw3xZgHDcjJCuNARjvHXAbS5bOpWUWFNvUr84zdGaY17m1/u2JMtK5lKrdvnqNHxQFkdwWCuL270+zMx6M2x6leI1xSFs4aDKgYQ6inHieNZE9p4j77iTc2Ui7azoMbNI1daO0FOwL4FTldMARmDWFPfbw=,iv:et9QpmS1QxXni1zhx+qY00CJceVwmvswHuM4GMyZaAQ=,tag:TnpiayJNmfYaMbMD2jIpcw==,type:str]
    version: 3.13.2
