apiVersion: v1
kind: Secret
metadata:
    name: pihole-password
    namespace: external-dns
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:2atE9jz4954pJv5bp9V+gJvpX2xqcR0hTSL615BTV1eU2KEmQX0Vt6N8jPo=,iv:3etnY6UAcuTLGrhDo99EgVKQ/ORhKWeDmSTV/rxh1go=,tag:BVXN2GJtZyFGmd0YviV3nw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUzhCcHJSVUlBYW5yYUo1
            U3ZNenN2U0F5ZEZBN0R3a3kzMW1tK3NwOTBRCjRaODJUZmFROTJIazN6UnFXS1Nw
            UXZaN2kzUTVZMkhJMk1PVFVhWFF0Nm8KLS0tIE9JZW1PTXV4WGk2K0dhbzJ2U2FX
            cmdBdTR2QmRtejZzczhhOWttMldDN28KFxP0n1vwWmLiuSV+SsM4jDNGFA31mXc/
            Qm9PY7RS0C5vgMsLViIdgQZKw4M3+qDBMSl2MYhlZQx3m5XcTG5xNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1da2cywfkg9hp6v39jvj9qcmqz4n8w3gm6nqj5vygu7e0zzgnp5psne9wlx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T22:08:14Z"
    mac: ENC[AES256_GCM,data:Gt8MfwoqtyqVhB1I2Ih4lIC8akHpSQ4rZ+7hLbCziHo2AnpJWy21FJ/RSWUEmwEmhNdyYhppx2Dhe1u0yDmXDP4CeMHeXIYrl76+slePbYOqqVSn5/kcoJmJim15DTPEOzZlCL4uWyROAfnprmTaAG6MVHNFweMM9StO69aDqeI=,iv:m4f3GLAKULh89JzSYgJT5NWd9yFsg4edLTibGMTOfJc=,tag:5pzMFM6g3U4UOBYlOkOe1Q==,type:str]
    version: 3.13.2
