apiVersion: v1
kind: Secret
metadata:
    name: smb-credentials
    namespace: media
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:QxjqSg==,iv:rpGg+1KPEdssq6T5pPcmnZjpnyQlLB6uWnKA7RRnKGo=,tag:rmhamKMNKrLhTZlkOsCjKQ==,type:str]
    password: ENC[AES256_GCM,data:v7TT3ufLFgmR+pCu2/6Op5ZNH7c=,iv:P/oI8iw2OGpFKnYT7y+S1Ug9FeU+3gAExa+aT8Uzqus=,tag:U9eQ+p6/sjvK3b4i4q9+jQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVy84WTgrQmVCSkJWT3FM
            OWo2TmVOdHpWME5PckhCdUM3RkxRMW1tdkI4CmdOdU1WMDdJSXFVMFRPaE9Lc2VG
            Sng0OEswS2ZrNmpVVE1hS0h2SWF0Y0kKLS0tIHN2V2lPRW56cEU3dWdLMi85a2Nk
            YVlnRlYrYlVYRTVXNGlCUGRrYitYVFEKW34WkLhEzr/tAqMnAwDsKRK4s4QVUK4p
            ypSuSFDrGJAXIyYIEpQaeQ5pKCp8F7KZXjal/a44Dw/t/QJr0hrmmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1da2cywfkg9hp6v39jvj9qcmqz4n8w3gm6nqj5vygu7e0zzgnp5psne9wlx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T03:12:20Z"
    mac: ENC[AES256_GCM,data:rsadkheMhSzBQ0Jl15kMklYL0hvcibqf7MRBRJfrMsweU327ll8lh1gGzvfikvF2Maq3T/mdYFb7tRwWsTa8FZFwsj8XuhdfLotM3hzifNbqEezh8pXj93m5eYQiYZM3VAfztuQVfbbwODKugtYcenekxCgpYSrw0SDT9q13pUA=,iv:IAb35lqiVNEKtla7Pdj/yenZfSt1toYQInRoqfrw1sg=,tag:4LwFKw8UP6bvo5aPMQDIGw==,type:str]
    version: 3.13.2
