crds:
  enabled: true
  keep: true
replicaCount: 2
podDisruptionBudget:
  enabled: true
  minAvailable: 1
resources:
  requests:
    cpu: 10m
    memory: 64Mi
webhook:
  replicaCount: 2
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
cainjector:
  replicaCount: 2
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
startupapicheck:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
