apiVersion: v1
kind: Secret
metadata:
    name: flux-canary
    labels:
        app.kubernetes.io/component: reconciliation-canary
        app.kubernetes.io/name: flux-canary
        app.kubernetes.io/part-of: flux
stringData:
    marker: ENC[AES256_GCM,data:TzaoCCg=,iv:mx4N25eNXyKb9rIXL/34wv9c0Y+eR1zey7/ig7+50lQ=,tag:G+pVakH4jnNNOwR4K0ZlxQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwOEV3c2Fjc2p2T3lPV0RS
            OUJLU2NnN0Jkc085QUtXQWNleHFPSExnTlRvCi90M29rc3F3S1BKazhCUzVGUDlE
            LzZ6bnIyWGdzR1l5R01VQzNBVk14REEKLS0tIFM4Zm16VU1FNEpGMlVwL2UxeHdy
            UHJDb21pZ3I0RS9GRjVQVkpVeXVMR2cKhTiEemxqu+kUyuoCt9vnhT7TkAnXt+3B
            nRlXgVCVryWsEJhBAsQW/bslhdDDWIFC3kiFjLCfltPZE50tB3A66Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1da2cywfkg9hp6v39jvj9qcmqz4n8w3gm6nqj5vygu7e0zzgnp5psne9wlx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T15:55:29Z"
    mac: ENC[AES256_GCM,data:OxFqOdygaOfNk5awOEYHnktA7aUYl8mwALwTcY2WkK6lC+y1lWRVYRYrruja8Ac90avb5GKEfvmA4ogTLXhvv0rZA+Tnv0zEVGUmdZtrbd4BVv4PQOBnnUYV29yytP4Yw4L7X5OXPBC0OggPQux80+Ic6t8vfeQx+xMp6Vft4FI=,iv:2NABCzlGD2jbintHzuZpw2tE7PKFViTIM9A+eU8zPKU=,tag:4yi58HaL6JJX7uDnjbH7Ew==,type:str]
    version: 3.13.2
