apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
type: Opaque
stringData:
    grafana-user: ENC[AES256_GCM,data:MysI4oY=,iv:Q9CYcWGJKrFVJIgX2OFlZwkVn03WPYNIze3Mr+S+BWM=,tag:STd8iFz/gw/4Kcw/lKf2hQ==,type:str]
    grafana-password: ENC[AES256_GCM,data:VTKN+KuwqvVSp7UkiTq+Uyz/iMp5UFyhL+NOxYin3Re/VX5KcAcgvw==,iv:nIGSuIKAkJ0lfY5xw6ufYBtY7iLycBsjx2LxMXBS/s0=,tag:p/dEirI2UzzyQO+/DY+a1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArN0JVT1plTnd2RTZuOGZX
            RmtXRm1NUkd2Y0ZkZTBRZG5oa1BqMXZYZFFVCnllTFdiTzZrZlZkdWRzVEpOR0xS
            U09CQUtGd25IL2g1ZEJnSUFHSUZlVEUKLS0tIHNqV0YrUXVzMC93VWVoVWVEdzRt
            V212NTdYek1FRXF3RnRKMmhsVERUZFEKO2YXMUKBFCRxidgkueyLTEgbqywr4h08
            9gJRZyt4F22hnG/6m3+8Ycq3xJpK/Ehigt/Vnhcll6q6+FnwiONaFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1da2cywfkg9hp6v39jvj9qcmqz4n8w3gm6nqj5vygu7e0zzgnp5psne9wlx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T23:06:55Z"
    mac: ENC[AES256_GCM,data:aDd7vLjibzkW1vmJl1V+wipc2Efls97o8LmEg3R0LnmRlRNBMSdBv2FEFVZ3ZH3W50T/mZnOS4dLgh8FmtmYnYD7Gw2E+wjaWXtT7MrDIDmwsBe2N9JupVsRtbYHe8/mm0pvolPScCFjoymBS/cJ9CKu8JFdpGc0CTHaKKAk1z0=,iv:pTFRnE55YSdyCQlHUA0VcLrueezDRhbTrJh/ihsRHW4=,tag:df3PHbOb0uIVUnh0VFjfWA==,type:str]
    version: 3.13.2
