apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
type: Opaque
stringData:
    grafana-user: ENC[AES256_GCM,data:vJYOzD0=,iv:IZgryDzBktfAfGzQzMLiLpaRczqXveQP7gqOqzgNHGc=,tag:C85T7uQwZGwQFh8AU19unA==,type:str]
    grafana-password: ENC[AES256_GCM,data:C2vYVBb+86vfKizwbO3tz2g+FoZTq2TaoYS1YFxyAZWBgrvAeLU=,iv:2AZAv79aqqHoJg5CqnXVaJab6bh7lESoBC5/QrwLoLo=,tag:i29VuCsyBGRMFId/iiJ2qg==,type:str]
    plex-token: ENC[AES256_GCM,data:277C8AjIdBsognVlR3wNW+5M9Xo=,iv:1X4dJx6mx7FN3dQx6czczWJsKlSITGtkNmvi3tyBWrQ=,tag:ZoDYNTjga30S5p739cnPlA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlb2VYMjI3RXpmMkdIT0p6
            NHpQY1d1N1V6Und2OFVOUEhWTzNmOE4rd21rClExZ0kveFBTTnNqRGtabVRQWDRp
            M0tDTTFQMUYzWmhEenpOL1AxTDRCNWcKLS0tIDZRNFFlNWdibHg0NDV5OE1UTEor
            RjBrT3JsRjREbWhPSW5IUVJVTGwxSWMK0dBLUV5QPoT3KHr82SL/KfTgWicrn6QD
            pZi8FQ5d9C9XTQ3U0ewDU96Mrau8aP9vtpFBzBgNwv2o2Kxydx3wzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1da2cywfkg9hp6v39jvj9qcmqz4n8w3gm6nqj5vygu7e0zzgnp5psne9wlx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T22:51:25Z"
    mac: ENC[AES256_GCM,data:d7SkYe26yhXyv3wpn0TnLghk1kU0/p6b85ASByUF4bwwltVvVwj6RQLcpYby9MI0sDW4TFodH0hRCQ++tsdKFCJCpAzLEBkokzJf4F2b+hrre/5gxJWevCohEiOr6sRQewXtVrWW62gFb8uQkTKsWdsPlRIgVrVJAXoDirAvdaI=,iv:HYdnw8Nge5N1/c3H7flD06rKEkxm8F29Mp2kv+tLNck=,tag:PI9Vb06rwO1HcEfnZ4WwSg==,type:str]
    version: 3.13.2
