---
apiVersion: v1
kind: Namespace
metadata:
  name: homepage
  labels:
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
    # Required for the HTTPRoute here to attach to the internal gateway.
    gateway.supermorphic.com/access: internal
