---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: longhorn
      version: 1.12.0
  driftDetection:
    mode: enabled
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 1h
  releaseName: longhorn
  storageNamespace: longhorn-system
  targetNamespace: longhorn-system
  timeout: 15m
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
      strategy: rollback
  valuesFrom:
    - kind: ConfigMap
      name: longhorn-values
      valuesKey: values.yaml
