---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cloudflare-api-token.sops.yaml
  - ./clusterissuers.yaml
  - ./networking-namespace.yaml
  - ./staging-certificate.yaml
