---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-lab-supermorphic-com-staging
  namespace: networking
spec:
  dnsNames:
    - "*.lab.supermorphic.com"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-staging
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
    size: 256
  secretName: wildcard-lab-supermorphic-com-staging-tls
  usages:
    - digital signature
    - server auth
