---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
  driftDetection:
    mode: enabled
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 1h
  releaseName: envoy-gateway
  storageNamespace: envoy-gateway-system
  targetNamespace: envoy-gateway-system
  timeout: 15m
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
      strategy: rollback
  valuesFrom:
    - kind: ConfigMap
      name: envoy-gateway-values
      valuesKey: values.yaml
